INSERT INTO CLIENT (ID, FIRSTNAME, LASTNAME) VALUES (1, 'JUAN', 'JOHACO');
INSERT INTO CLIENT (ID, FIRSTNAME, LASTNAME) VALUES (2, 'PEDRO', 'PIEDRA');
INSERT INTO ITEM (ID, NAME) VALUES (1, 'PAPEL');
INSERT INTO ITEM (ID, NAME) VALUES (2, 'CREMA');
INSERT INTO PURCHASE (ID, DATE_TIME, POINT, CLIENT) VALUES (1, TO_DATE('2020-12-12', 'YYYY-MM-DD'), 290, 1);
INSERT INTO PURCHASE (ID, DATE_TIME, POINT, CLIENT) VALUES (2, TO_DATE('2020-12-12', 'YYYY-MM-DD'), 200, 2);
INSERT INTO PURCHASE_DETAIL (PURCHASE, ITEM, VALUEUNIT, CANT) VALUES (1,1,100,1);
INSERT INTO PURCHASE_DETAIL (PURCHASE, ITEM, VALUEUNIT, CANT) VALUES (1,2,120,2);
INSERT INTO PURCHASE_DETAIL (PURCHASE, ITEM, VALUEUNIT, CANT) VALUES (2,1,200,2);